## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
#Q1-1
frame = pd.DataFrame(data)
print(frame)
#Q1-2
frame2 = frame[((frame["job"]== "psychologist") | (frame["job"]== "teacher")) & ( frame["num_cars"] > frame["family_size"])]
print("\n",frame2)
#Q1-3
frame3 = frame[(frame["family_size"] <= 2) & ( frame["num_cars"] >= 1)]
print("\n",frame3)
#Q1-4
print("\nNumber of unique jobs:", len(set(data["job"])))


     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1

    name           job  family_size  num_cars
5  Lisa  psychologist            3         4

     name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1

Number of unique jobs: 4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
weights.groupby(fruit).mean()

apple     4.50
banana    5.75
carrot    5.75
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
#Q3-1
sortedCourse = np.sort(course_name)
indices = np.argsort(course_name) 
print(indices)
#Q3-2
for i in course_name:
  if i[0] == "P":
    print(True)
  else:
    print(False)


[1 3 0 2 4]
True
False
False
True
False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
#Q4-1
flipped = np.flip(student_id)
print(student_id)
print(flipped)
#Q4-2
sorted = np.sort(student_id)
flip_sorted = np.flip(sorted)
print(flip_sorted[:3])

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
[6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
multiple_of_three = np.arange(0,100,3)
print("Sum of multiples of 3 below 100:", np.sum(multiple_of_three))
multiple_of_five = np.arange(0,100,5)
print("Sum of multiples of 5 below 100:", np.sum(multiple_of_five))

# Hint: you can use arange to start off

Sum of multiples of 3 below 100: 1683
Sum of multiples of 5 below 100: 950


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#Q6-1
import numpy as np
arr = np.arange(12).reshape(3,4)
arr[:,[2,1]] = arr[:,[1,2]]
print(arr)

#Q6-2
arr2 = np.arange(12).reshape(3,4)
arr2[[0, 1]] = arr2[[1, 0]]
print(arr2)


[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
